### ISSUE TITLE
The issue about the VQ part

### ISSUE THREAD

**Issue by YxuanAr** [chenguolin/InstructScene#3]
Hi Guolin,

Thanks for your great work and congrats on the ICLR accepted!

But when I try to VQ the feature from scratch, I found I get an error in train_objfeatvqvae.py:
```python
    train_objfeats = [
        eval(f"obj.{config['model']['objfeat_type']}_features")
        #print(f"{obj}.{config['model']['objfeat_type']}_features")
        for obj in train_objects
    ]
    train_objfeats = np.stack(train_objfeats, axis=0)
    kwargs = {
        "objfeat_min": train_objfeats.min(),
        "objfeat_max": train_objfeats.max()
    }
``` 
I get an error that:
"objfeat_min": train_objfeats.min(),
  File "/anaconda3/envs/cdpm/lib/python3.10/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'NoneType' and 'NoneType'

and I found that all the train_objfeats are none.

I noticed that you mentioned we should **update the quantization indices in the dataset (stored in dataset/InstructScene/threed_front_<room_type>/<scene_id>/models_info.pkl)**, but I am not sure how we can do that.

Can you help me to give an example?

Thanks a lot.

**Comment by chenguolin** [comment]
Hi @YxuanAr,

Thanks for your interest in our project.

1. Did you download the provided dataset properly? The line you mentioned (`eval(f"obj.{config['model']['objfeat_type']}_features")`) runs the following codes: https://github.com/chenguolin/InstructScene/blob/d6950e929de77e26e07acbe5909269bc8252f827/src/data/threed_front_scene.py#L242-L247, and path to the features is:
https://github.com/chenguolin/InstructScene/blob/d6950e929de77e26e07acbe5909269bc8252f827/src/data/threed_front_scene.py#L207-L212. Because the path of feature files does not exist, you got all None returned.

2. To update quantization indices for a new fVQ-VAE, we should run the new model to quantize every object feature by: https://github.com/chenguolin/InstructScene/blob/d6950e929de77e26e07acbe5909269bc8252f827/src/models/objfeat_vqvae.py#L61-L70. `model_info.pkl` stores the quantization indices of all the objects **in one scene**. So we should update the quantization indices of objects in the corresponding scene in `model_info.pkl`.

**Comment by YxuanAr** [comment]
Hi Guolin，

Sorry for my delay reply. I have solved the issue with changing the file's location. 

Thanks for your reply!
